name: staff_attendance_app
description: A Flutter-based staff attendance monitoring app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase core services
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.16.0

  # Location and biometric authentication
  geolocator: ^12.0.0
  local_auth: ^2.1.7

  # UI helpers
  fluttertoast: ^8.2.4
  csv: ^5.0.1
  path_provider: ^2.0.15
  media_store_plus: ^0.1.3
  permission_handler: ^11.3.0

  # Optional (uncomment if needed in the future)
  # firebase_storage: ^11.6.0
  # firebase_crashlytics: ^3.5.0
  # firebase_messaging: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
