// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZSvd21Qd7e3Vkw_ml9gTFGH38Pq0KPD8',
    appId: '1:662379852010:web:41cf02fb34f8e8f09de793',
    messagingSenderId: '662379852010',
    projectId: 'staff-attendence-monitoring',
    authDomain: 'staff-attendence-monitoring.firebaseapp.com',
    storageBucket: 'staff-attendence-monitoring.firebasestorage.app',
    measurementId: 'G-CQV1WY8CGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcglHwyGoLxfv_gu4_v9Vb7wj13jnULjg',
    appId: '1:662379852010:android:6a1ce82f8532baf49de793',
    messagingSenderId: '662379852010',
    projectId: 'staff-attendence-monitoring',
    storageBucket: 'staff-attendence-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNUch-uLg80WfaMDVyoYGjA10zlI3Cms',
    appId: '1:662379852010:ios:9734513bf2a915869de793',
    messagingSenderId: '662379852010',
    projectId: 'staff-attendence-monitoring',
    storageBucket: 'staff-attendence-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.staffAttendanceMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNUch-uLg80WfaMDVyoYGjA10zlI3Cms',
    appId: '1:662379852010:ios:9734513bf2a915869de793',
    messagingSenderId: '662379852010',
    projectId: 'staff-attendence-monitoring',
    storageBucket: 'staff-attendence-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.staffAttendanceMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZSvd21Qd7e3Vkw_ml9gTFGH38Pq0KPD8',
    appId: '1:662379852010:web:dc18931dfb0475ef9de793',
    messagingSenderId: '662379852010',
    projectId: 'staff-attendence-monitoring',
    authDomain: 'staff-attendence-monitoring.firebaseapp.com',
    storageBucket: 'staff-attendence-monitoring.firebasestorage.app',
    measurementId: 'G-Y518E1Q7TK',
  );
}
